### ISSUE TITLE
document TOML expectations (and undocumented fields)

### ISSUE THREAD

**Issue by tamsky** [globeandmail/ansible-role-amazon-cloudwatch-agent#2]
I'm getting the feeling that manually populating the TOML is not a supportable strategy.

First reason:

https://github.com/globeandmail/ansible-role-amazon-cloudwatch-agent/blob/master/ExampleCfgs/group_files/awscwa_cfg/generic/amazon-cloudwatch-agent.toml.j2#L49-L50
has the fields
```
      timestamp_layout = "{{logfile.timestamp_layout}}"
      timestamp_regex = "{{logfile.timestamp_regex}}"
```

but the TOML does not have a published schema, 
and there is no corresponding field for either in the JSON schema...
-- therefore these fields appear to be undocumented.

Do you have any proposals as to how someone using this ansible-role should populate the above two fields?

It appears to me that keeping to using the JSON schema and letting the `start-amazon-cloudwatch-agent` script perform the JSON->TOML conversion is the only supportable method of using it.

Thoughts?

What tweaks did you find you needed to make between the JSON and the generated TOML?
Maybe you can share/document your tweaks as comments here or in the TOML?

**Comment by tamsky** [comment]
Additionally: the fact that the new golang based cloudwatch agent is closed-source should make folks' eyeballs pop out.

I recommend everyone avoid the unified agent until source is released.

**Comment by 1adam** [comment]
Yep, working directly with the TOML is less than ideal, but (at least at the time of creating this role) it was necessary to properly parse the syslog timestamp.

Those two fields,
```
timestamp_layout = "Jan 2 15:04:05"
timestamp_regex = "^.*(\\w{3} \\s{0,1}\\d{1,2} \\d{2}:\\d{2}:\\d{2}).*$"
```
show up in the TOML when the bin/config-translator is run on the JSON.

The problem was that, in syslog, the timestamp could be something like this (two spaces following short month) and the resultant timestamp_regex the config-translator was spitting out wasn't able to account for the extra space.
```
Oct  1 01:02:03
```

`timestamp_layout`, as far as I understand it, is populated automatically according to the pattern specified in the JSON as `timestamp_format`

My tweak was simply to account for the possibility of more than one space, and match only at the beginning of a line:
`timestamp_regex = "^(\\w{3}\\s+\\d{1,2} \\d{2}:\\d{2}:\\d{2}).*$"`

All that being said, the regex I pasted above (the first one; not my tweak) was just pulled from a TOML freshly created using the config-translator -- and it looks like it will now correctly account for the possibility of the double space, so maybe there's no longer a need for the skip-the-JSON hackery.

**Comment by tgam-abarrett** [comment]
custom/manual TOML has been dropped
